FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.2

ENV name=node.name
ENV cluster.name=jaeger-cluster
ENV discovery.type=single-node
ENV http.host=0.0.0.0
ENV transport,host=127.0.0.1
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false

EXPOSE 9200