version: "3.9"

services:
  elasticsearch:
    image: sbsglobalweregistry.azurecr.io/sbs-elasticsearch-jaeger:7.9.3
    container_name: elasticsearch
    networks:
      - elastic-jaeger
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    mem_limit: 1g
    restart: on-failure
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
    volumes:
      - data1:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
    - elasticsearch
    networks:
    - elastic-jaeger

  jaeger-collector:
    image: sbsglobalweregistry.azurecr.io/sbs-jaeger-collector:1.0.0
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "14250:14250"
      - "9411:9411"
    networks:
      - elastic-jaeger
    restart: always
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      - elasticsearch

#  jaeger-agent:
#    image: sbsglobalweregistry.azurecr.io/sbs-jaeger-agent:1.0.0
#    hostname: jaeger-agent
#    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#    networks:
#      - elastic-jaeger
#    restart: on-failure
#    environment:
#      - SPAN_STORAGE_TYPE=elasticsearch
#    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1G
#    depends_on:
#      - jaeger-collector
#
#  jaeger-query:
#    image: sbsglobalweregistry.azurecr.io/sbs-jaeger-query:1.0.0
#    environment:
#      - SPAN_STORAGE_TYPE=elasticsearch
#      - no_proxy=localhost
#    ports:
#      - "16686:16686"
#      #- "16687:16687"
#    networks:
#      - elastic-jaeger
#    restart: on-failure
#    command: [
#      "--es.server-urls=http://elasticsearch:9200",
#      "--span-storage.type=elasticsearch",
#      "--log-level=debug"
#    ]
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    depends_on:
#      - elasticsearch

volumes:
  data1:
    driver: azure_file
    driver_opts:
      share_name: elk
      storage_account_name: elasticjaeger

networks:
  elastic-jaeger:
    driver: bridge 
